### ISSUE TITLE
Small typo seems to be throwing out an error

### ISSUE THREAD

**Issue by alexdodkin** [darthsoup/php-whmcs-api#11]
Fatal error:  
Uncaught Symfony\Component\OptionsResolver\Exception\UndefinedOptionsException: The option "gid" does not exist.

Fix:
In the file > API > Order.php
Line 149 it says $resolver->setDefined(['pid', '**gpid**', 'module']);
I believe this should be $resolver->setDefined(['pid', '**gid**', 'module']);

**Comment by darthsoup** [comment]
thanks for the report. should be fixed with the newest version 1.3.2
