### ISSUE TITLE
Issues on addOrder function in orders.php

### ISSUE THREAD

**Issue by alexdodkin** [darthsoup/php-whmcs-api#12]
A couple of small issues here, in orders.php, for the addOrder function we also need to define the "domain" parameter, which is currently missing.

`$resolver->setDefined([
            'clientid', 'paymentmethod', 'domain', ` 

Secondly, on the line

`$resolver->setRequired(['clientId', 'paymentmethod']);`

The required parameter "clientId" has a capital "i" but it should be all lowercase, otherwise an error is thrown out.

**Comment by darthsoup** [comment]
thanks for finding, its fixed with 1.3.3
