### ISSUE TITLE
PHP Fatal error:  Uncaught DarthSoup\WhmcsApi\Exception\AuthenticationException

### ISSUE THREAD

**Issue by alexdodkin** [darthsoup/php-whmcs-api#14]
When the API credentials are not correct, there is an uncaught exception error.

PHP Fatal error:  Uncaught DarthSoup\WhmcsApi\Exception\AuthenticationException: Invalid or missing credentials in /darthsoup/php-whmcs-api/src/HttpClient/Plugin/ExceptionHandler.php:63

This seems to be due to this part of the request in the ExceptionHandler.php file

`throw self::transformMessageToException(
$status,
ResponseFormatter::errorMessage($response) ?? $response->getReasonPhrase()
);`

The second part ($response->getReasonPhrase()) does not seem to have any place to catch the error that comes back.

Easy way to test this, is just make the credentials incorrect, by change the WHMCS url, or changing the api or secret.

PS. thanks for fixing the other issues, great job!

**Comment by darthsoup** [comment]
Hi,

sorry for the late response. But I can not recreate this error with the Fatal Error. Which version of whmcs are you using?
