### ISSUE TITLE
Cannot Publish Provider on Laravel 9

### ISSUE THREAD

**Issue by kingrootid** [darthsoup/php-whmcs-api#16]
`config/app.php
 'aliases' => Facade::defaultAliases()->merge([
        // 'ExampleClass' => App\Example\ExampleClass::class,
        'Whmcs' => DarthSoup\Whmcs\Facades\Whmcs::class
    ])->toArray(),
`

`php artisan vendor:publish --provider=DarthSoup\Whmcs\WhmcsServiceProvider`

**INFO  No publishable resources for tag [].**  

this package not support for latest laravel or what ?

**Comment by darthsoup** [comment]
The repository has nothing to do with my [laravel whmcs](https://github.com/darthsoup/laravel-whmcs) package. This one here only contains the api.

Try with `php artisan vendor:publish --provider="DarthSoup\Whmcs\WhmcsServiceProvider"`. Fixed that in the readme.
