### ISSUE TITLE
Authentication validateLogin needs a way to validate logins that are using email (or am I missing it?) | WHMCS 8.5.1

### ISSUE THREAD

**Issue by asdevroxy** [darthsoup/php-whmcs-api#17]
## The Issue
I am trying to use this API to validate the logins of WHMCS users using their email/password combo.
As far as im aware (I MIGHT be missing it, idk), this API only supports doing so using username.
Trying to use an email in this username field doesn't work, it returns `Invalid Email or Password`.

### WHMCS Version
Version 8.5.1
### WHMCS PHP Version
Version 7.4.33

### Laravel Version
10.4.1

### Laravel PHP Version
8.1.6

### Code I'm running
`\Whmcs::Authentication()->validateLogin("*my test email*", "*my test password*")`

### The error screen
![image](https://user-images.githubusercontent.com/58989446/228889006-370ea4c1-09a8-436e-bc1c-c8fd89a0ffd0.png)

**Comment by darthsoup** [comment]
Your code is right, the api was using the wrong parameter.
I fixed it with the newest release.
