### ISSUE TITLE
Add access key parameter in the Authentication.php

### ISSUE THREAD

**Issue by dekts** [darthsoup/php-whmcs-api#3]
Hi Kevin,

This will lead to the following error message when attempting to log in with a username and password. I have found a solution to fix this IP related issue in WHMCS.

**Invalid IP 2405:201:2023:685c:111f:4195:bb4a:3575**

[Solution](https://stackoverflow.com/questions/42297983/whmcs-error-occured-invalid-ip-1-when-using-external-api): It works by defining a secret key/passphrase in the WHMCS configuration.php file which is then passed into all API calls. To configure it, add a line as follows to your configuration.php file in the root WHMCS directory

I checked this package and found a file named **darthsoup/php-whmcs-api/src/HttpClient/Plugin/Authentication.php**. This file has a method called **buildAuth()** on line number 61, and I have added a new parameter to it in the following case.

```
case Client::AUTH_LOGIN_CREDENTIALS:
    $authBag['username'] = $this->identifier;
    $authBag['password'] = md5($this->secret);
    $authBag['accesskey'] = "YOUR_ACCESS_KEY"
```

As you can see, I added the third parameter to add the access key so I don't have to add my IP address every day to the WHMCS platform to make it trusted or whitelisted.

Add the 3rd parameter as an optional parameter in this package, and many members who are experiencing this issue will be fixed.

**Comment by darthsoup** [comment]
makes sense, I will see how I can implement that

**Comment by darthsoup** [comment]
Released a new version which provides the accessKey functionality. See the Readme for instructions :)
