### ISSUE TITLE
The option "search" does not exist

### ISSUE THREAD

**Issue by jacksontong** [darthsoup/php-whmcs-api#4]
I run the example and got this error
```php
$client->client()->getClients(['search' => 'firstname']);
```
```
Symfony\Component\OptionsResolver\Exception\UndefinedOptionsException 

  The option "search" does not exist. Defined options are: "limitnum", "limitstart", "orderby", "sortOrder", "sorting", "status".
```
I don't see `search` in [createOptionsResolver](https://github.com/darthsoup/php-whmcs-api/blob/abf5faa6fc103c63e0a2a8bc8b92b9937373352d/src/Api/AbstractApi.php#L54)

**Comment by darthsoup** [comment]
Well, I seem to have missed something there! Will fix this in the next release

**Comment by darthsoup** [comment]
Released a new version. Give it a try :)
