### ISSUE TITLE
 The option "clientid" does not exist. Defined options are: "limitnum", "limitstart", "orderby", "search", "sortOrder", "sorting", "status".

### ISSUE THREAD

**Issue by mrl22** [darthsoup/php-whmcs-api#8]
Hello,

Thank you for a great package. I am unable to get specific client details due to the clientid parameter not being allowed.

```
$client->client()->GetClientsDetails(['clientid' => 1]);
```

```
 The option "clientid" does not exist. Defined options are: "limitnum", "limitstart", "orderby", "search", "sortOrder", "sorting", "status".
```

[https://developers.whmcs.com/api-reference/getclientsdetails/](https://developers.whmcs.com/api-reference/getclientsdetails/)

**Comment by mrl22** [comment]
I have got around this for now by using:

```
$client->custom()->GetClientsDetails(['clientid' => 1]);
```

**Comment by darthsoup** [comment]
Hi,

I am aware of it since yesterday :S.
Somehow I misunderstood how the optionresolver works, and currently I am trying to sort all these issues...

**Comment by mrl22** [comment]
Hi

Not a problem, I used your package in a project I finished yesterday. https://github.com/webforward/whmcs-3cx-contacts-sync

**Comment by darthsoup** [comment]
commited some changes. should work now
